server:
  port: 8001
eureka:
  instance:
    hostname: eureka8001
  client:
    service-url:
      defaultZone:
        http://eureka8002:8002/eureka/
    register-with-eureka: false
    fetch-registry: false